name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger only when pushing tags like v0.1.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Upgrade pip and install build tool
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build the distribution
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
